#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ERROR_COUNT_ARGS 1
#define ERROR_FLAG 53
#define ERROR_INVALID_FILE 3
#define ERROR_EMPTY_FILE 4
#define ERROR_ENTRY_PRODUCT 5
#define ERROR_NOTHING_FOUND 6
#define MAX_LEN_NAME 31
#define MAX_LEN_MANUFACTURER 16

#endif
